name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest]
        ocaml-version: [ '4.10.0' ]

    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v1.1.11
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Dependencies
      run: opam pin dafny-of-python && opam install dune && opam install ./ --deps-only && dune external-lib-deps --missing @@default
    - name: Build
      run: opam exec -- dune build
